- src/x_spider.c
Dustin Sallings had submitted an earlier pull request adding IPv6 support to the TCP server. The request relied on the OS mapping IPv4 requests to an IPv6 socket, which some OS's such as FreeBSD do not support. 
This request takes a different approach of creating more than one socket and using poll() to determine when a connection is pending. This should avoid the issue seen with the previous pull request. I did make use of Dustin's addr_str() function. 
I have tested this on my Mac and it accepts connections via both IPv4 and IPv6. Two sockets are listed as listening. I do not have easy access to test on other platforms at the moment.
I may add UDP support later, but that will be a different pull request. (I like smaller code changes.)
> Add support for IPv6 to the x_spider TCP server

- AUTHORS
- README.CYGWIN
I attempted a compile and install of the current git source under Cygwin, trying to reference the list of dependencies in README.CYGWIN.  The dependencies did not align with the current packages offered by Cygwin.  Packages were renamed, replaced or eliminated.  GDAL is now directly supported by Cygwin.  The documentation has been updated accordingly based upon several actual compiles/installs of Xastir under Cygwin on Windows 10.  This was tested under x64.
> README.CYGWIN packages dependencies required update

- README.CYGWIN
As a followup to #13, I conducted a complete review and substantial rewrite.  Much information was out of date, referred to sources no longer available, and dealt with Cygwin or Windows issues long since resolved.  Many references were from XP and earlier, which are no longer supported.  A better installation method is provided so that the user does not have to click through Cygwin menus selecting packages.  Reference to the new Windows 10 bash capabilities is provided.  Extensive testing and proofreading was done to validate all changes/updated information.  A running system was configured based on the document and kept online for several days to assure stability.
> Extensive update of README.CYGWIN

- src/interface.c
We weren't breaking out of connect() loop on success. This could either lead to the address with the lowest priority being used, or possibly failing to connect at all.
Make sure the channel FD is set to -1 when we close the socket. Otherwise we could try to close it again when the same FD number is being used by another interface.
> Fix bugs in previous IPv6 update

- src/db.c
Hi,
I'm running some tests and use the APRS packet type "User-defined" therefore. Xastir however doesn't relay those packets to the Internet servers.
73 Sven DL7AD
> Allow user-defined packets to be sent to APRS-IS

- README.OSM_maps
Remove references to no-longer-available tile sources. Add description of web Mercator projection and tiling scheme, with Wikipedia links. Correct minor punctuation errors. Note: Cloudmade has been out of the map tile business for at least 5 years.
> update OSM README and add map tile info

- configure.ac
- src/main.c
Xorg 1.7.5 had a bug in the X server that broke pop-up menus in Motif
programs.  This bug was fixed very quickly, but not before Xorg 1.7.5
made it into some Long Term Support distros.  Thus, we had to hack in
a workaround that tested XmVersion and did different things.
All distros that had this broken server have long since passed their
end of life.  I am now removing this hack.
Should not be merged until pull request #48 is merged, at which point this branch should be rebased onto that fix.  remove "WIP" tag when that happens.
Closes issue #27.
> Remove hack for Xorg 1.7.5

- src/Makefile.am
- src/main.c
Insertion of the compilation date and time into the Xastir binary
breaks binary reproducibility, a feature desired (maybe even demanded)
by some Linux package management systems.
This commit removes the compile date and time from the "compiledate.c"
and instead only inserts the git sha-1 (which it was already doing)
if, and only if, we're building out of a git repo.
Doing this makes the binary produced from any Xastir code base
identical (i.e. with the same MD5 checksum) to any other binary built
on the same system with the same libraries from the same code base.
This closes issue #51.
> Make Xastir build reproducible

- src/Makefile.am
- src/dlm.c
- src/dlm.h
- src/interface.c
- src/map_OSM.c
- src/map_WMS.c
- src/map_geo.c
- src/map_tiger.c
Some bug fixes and a Download Manager to allow parallel background downloading of OSM tiles.
Really speeds up map display on high-latency connections (eg satellite internet)
> Download Manager

- src/main.c
This commit adds a "-V" to Xastir that causes it to display the
current version number (with git SHA-1 if appropriate) and exit.
Closes #59
> Add a '-V' CLI option to display version

- src/gps.c
- src/interface.c
- src/main.c
GLONASS receivers send $GNGGA sentences instead of $GPGGA sentences, and
$GNRMC instead of $GPRMC.  But the only difference between these
sentences is the GN instead of GP --- the data is identical.
This appears to be the reason that users of the DRAWS hat are unable
to use this device with Xastir, even though it appears to work with
all other programs that consume NMEA sentences.
This commit attempts to recognize GGA and RMC sentences irrespective
of whether they begin with "$GP" or "$GN".  It is tested so far only
with GPS receivers, and it doesn't break those.  I'm adding this on a
branch so that users of the DRAWS hat can test it out before we
actually merge into master.
If it works, this closes #53
> Add support for GNGGA and GNRMC sentences

- .travis.yml
- scripts/Makefile.am
Add a .travis.yml that builds for Linux (two iterations) and MacOS.
Fix a bug where now that there is no *.sh files in the scripts
directory a chmod in "make install" was failing.
(This is a small enough mod that the only reason I am doing a pull request is to test the Travis-CI integration.)
> Add Travis-ci configuration and fix install bug

- src/x_spider.c
If the UDP x_spider server couldn't open any ports (such as due to
another xastir process having them open) the child would return to
the main control logic of xastir, leading to two copies of xastir
running and duplicate windows appearing. Add an exit(1) after the
call to UDP_Server() so this can't happen. This fixes #65.
The TCP server didn't use return, but I added an exit(1) after the
call to TCP_Server() just to be safe.
I also fixed some warnings on MacOS compiles. This helps with
issue #24.
> Ensure x_spider children don't return

- src/alert.c
- src/datum.c
- src/db.c
- src/draw_symbols.c
- src/gps.h
- src/igate.c
- src/interface.c
- src/main.h
- src/objects.h
- src/rtree/index.c
- src/rtree/split_l.c
This PR removes a number of warnings from the Xastir build on GCC and Clang builds (linux and OS X).
- It addresses only warnings from the rtree code, alert.c, datum.c, db.c, igate.c and interface.c.
- It completely removes all warnings from rtree and alert.c on all platforms.
- It removes all warnings from datum.c on Linux, but leaves a few meaningless warnings about extended ASCII characters in strings from Clang on OS X.
- It removes most warnings from db.c on all platforms, but leaves a few warnings about fread return values being discarded on Linux.
- It removes numerous unused-but-set warnings from draw_symbols.c.  The same commit that does that also fixes some indentation errors in that file --- the file was wildly out of compliance with project standards.  The same commit also …
> Remove some warnings

- src/map_shp.c
I've started playing with using clang's "-fsanitize=address" feature
to look for bugs. When shapefile maps were enabled it crashed on a
read buffer overlow. We were reading the value from a char array
and then checking to see if the index was in bounds. Reverse it
so we check for in bounds first.
> Reorder bounds checking for while loop in draw_shapefile_map

- src/location_gui.c
We were passing 200 into sort_input_database as the size of name,
which was only 100 in size. Switch the two hardcoded array sizes
in jump_sort() to use sizeof().
> Fix buffer overflow in jump_sort()

- src/map_dos.c
We're now checking fread and fgets return codes for 0, but doing
nothing if found. The original code ignored the return code entirely
so this should be the same net effect, yet get rid of compiler
warnings. Partial fix for bug #24.
> Check fread and fgets calls

- src/map_geo.c
- src/map_tif.c
This is a WHITESPACE-ONLY pull request.  It removes a handful of "misleading indentation" warnings when building with GCC 6 or GCC 8.  A misleading indentation warning is emitted when this sort of thing is found:
if (foo)
bar;
baz;
This is indented as if baz is inside the if, but it is not guarded by the if.  
I did this by reindenting map_geo.c and map_tif.c according to project standards, which not only removed the warnings but also fixed some other abuses of indentation style.
No code changes or comment deletions were made in this series of commits.  It took great restraint not to blow away (or even re-indent) blocks of commented-out code.  But I did in fact exercise that restraint and change nothing but white space.
Addresses more warnings per bug #24.
> Remove "misleading indentation" warnings from two files

- src/map_geo.c
map_geo.c was throwing a warning about a set-but-unused variable, atb on my BSD box and on Rasbian (gcc 8 and gcc 6, respectively):
```
../../Xastir/src/map_geo.c:578:19: warning: variable 'atb' set but not used [-Wunused-but-set-variable]
XpmAttributes atb;              // Map attributes after map's read into an XImage
^~~
```
This variable is wrapped in an ifdef:
```
#ifndef NO_XPM
XpmAttributes atb;              // Map attributes after map's read into an XImage
#endif  // NO_XPM
```
and NO_XPM is set like this:
```
#if !(defined(HAVE_LIBXPM) || defined(HAVE_LIBXPM_IN_XM)
)
#define NO_XPM 1
#endif  // !(HAVE_LIBXPM || HAVE_LIBXPM_IN_XM)
```
That is, if configure did not find libxpm, NO_XPM is defined to 1 and the atb variable is not declared or set, and if xpm is found, it is declared …
> Fix map_geo MAGICK/XPM ifdefs

- src/map_geo.c
In commits b071954 and 7815dd9 (and possibly others associated with
PR #40), the GetIndexes function (present in both ImageMagick and
GraphicsMagick, and deprecated in both) was coded around so that if
we've got newer versions of the library, we use the new API, and if we
have an older version, we use the older API.
But #40 only fixed these deprecated uses in a few files, and mised the
one usage in map_geo.c
This commit copies over the fix verbatim from map_OSM.c, and shuts up
the deprecation warning.
Fixes #81.  Also shuts up warnings per #24.
> Fix deprecated GetIndexes usage

- src/main.c
Very simple changes but they get rid of most of the main.c compiler warnings. Partial fix to bug #24. Commenting out unused Widgets which aren't needed for some GUI elements.
> Commenting out unused variables in main.c

- src/main.c
- src/maps.c
Checking return values to get rid of compiler warnings, part of
remedies for bug #24. Also added a couple of missing initializers
in main.c for aircraft and ships.
> Check return values, add initializer

- src/interface.c
De-referencing a pointer to get rid of the warning: "comparison
between pointer and zero character constant" that shows up with
the gcc8 compiler.
> De-referencing pointer correctly to remove warning

- src/list_gui.c
Station_List_fill gets called repeatedly. Each run it
would add a callback to the icon button. On the next run
it would free the string that was passed to the callback
but not delete the old callback. Over time we would develop
a stack of old callbacks on the icon button that would
point to freed strings.
Add logic to remove the existing callback before we free
the string from the previous run.
Fixes #88
> Fix use after free bug in Station_List_fill

- src/db.c
If strings were empty a accessing strlen(-1) goes out of bounds.
Add a strlen() > 0 check.
Fixes #91
> Fix strlen()-1 buffer overflow in display_station()

- .travis.yml
This was a suggestion by Tom Russo. Trying to get the Travis-CI config as clean and modular as possible. Compiles fine.
> Move gcc8 stuff from install to before_script tag

- INSTALL
A small update to INSTALL: Add a note about libgc packages for OpenSUSE.
> Add note about libgc packages for SuSE

- src/map_OSM.c
- src/map_geo.c
- src/map_shp.c
Add ifdef's for HAVE_MAGIC around multiple variables and functions
that were throwing compiler warnings when the flags:
--without-graphicsmagic --without-imagemagick
were used. Fixes more compiler warnings from bug #24.
> Add ifdef's for HAVE_MAGIC

- src/db.c
- src/interface.c
- src/main.c
- src/map_shp.c
- src/util.c
Gcc7 emits a warning message if a switch case falls through to the
next case (unless it's the last case statement in the switch). By
adding specific comments the compiler is looking for, it shuts up
about the fall-through.  This is part of the solution for bug #24.
The proposed fixes only add comments: They don't change the
functionality of the switch case statements in any way.
> Add "fallthrough" comments to switch cases

- src/popup_gui.c
Change sprintf to xastir_snprintf to avoid warning: "may write a
terminating nul past the end of the destination". This results in
new warning: "output may be truncated", which is the same warning
we get again and again from use of the "xastir_snprintf" call.
> Avoid write past end of string

- src/dlm.c
This should fix any GUI threading issues in dlm.c. I commented out the Xm function call, the write to the status line, the variable being used for the string and the xastir_snprintf() that set the variable.
Once this has undergone a bit of testing I can go in and remove those bits altogether. That can be the last step of the bug report before it is closed (assuming this attempt is successful).
> Dlm threading

- .vimrc
- Davis/.vimrc
- LaCrosse/.vimrc
- callpass/.vimrc
- config/.vimrc
- help/.vimrc
- intl/.vimrc
- po/.vimrc
- scripts/.vimrc
- src/.vimrc
- src/rtree/.vimrc
- symbols/.vimrc
Updating VIM config files to new Xastir project coding standard of 2-spaces per indent.
> Updating .vimrc to new coding standard: 2 spaces

- src/gps.c
- src/main.c
NMEA sentences are:
$\<talker\>\<sentencetype\>,...
where \<talker\> is a two-character identifier representing the device
type.  The rest of the string is defined in the standard and doesn't
depend on the talker id.
Until commit 2264a035 (which merged PR#58), Xastir only recognized the
GP talker (GPS).  PR #58 added support for GN, GA, GL and GB.  But
there are many other talker IDs out there, and issue #121 calls for
yet another, $II.
This commit simply makes Xastir ignore the talker ID and look only for
the pattern "$..GGA" or "$..RMC" (where "." is regexp-speak for "any
character").
Issue #121
Issue #53
PR #58
> Make Xastir recognize GGA and RMC sentences from any talker

- callpass/callpass.c
Flawfinder (Python) found dangerous string functions in callpass. The
code has been rewritten to avoid those functions plus formatted to our
new code formatting rules.
> Swap out dangerous string functions in callpass

- src/bulletin_gui.c
- src/db.c
- src/draw_symbols.c
- src/forked_getaddrinfo.c
- src/geocoder_gui.c
- src/interface_gui.c
- src/list_gui.c
- src/locate_gui.c
- src/location_gui.c
- src/main.c
- src/maps.c
- src/maps.h
- src/messages_gui.c
- src/objects.c
- src/popup_gui.c
- src/track_gui.c
- src/view_message_gui.c
- src/wx_gui.c
We don't currently use lclint, the compiler find unused parameters
anyway and we have notation already in the code for that. The lclint
annotations add extra clutter to the function declarations. These
annotations are out-of-date as well. Solves issue #136.
> Remove lclint annotation "@unused@"

- .travis.yml
- configure.ac
- src/Makefile.am
- src/main.c
- src/map_shp.c
- src/shp_hash.c
- src/shp_hash.h
Years ago, Xastir's shapefile support always read an entire shapefile
if any part of the shapefile's bounding box intersected the current
map screen.  That could be enormously expensive when a shapefile had a
very large number of objects in it, only a small number of which were
actually on screen.
In 2004 (commit 7c9a474) I added an experimental feature where instead
of sequentially reading an entire shapefile only to find that only a
few objects in it were visible, a spatial index (R-tree data
structure) would be built from a shapefile the first time it was
read.  From that point forward, all reading of the file is done by
searching the spatial index for shapes that intersect the screen's
bounding box, and these individual objects are read via random access.
At that time, because it was …
> Make "rtree" the only shapefile reading method

- acinclude.m4
Since the earth was cooling and Xastir used ImageMagick, we've used
the existence of the script "Magick-config" to conclude whether
ImageMagick was installed or not, and if it was, we used this script
to get Magick to tell us what CFLAGS, LDFLAGS, and LIBS to use to
build with Magick support.
Magick 6 deprecated this script in favor of one called
MagickCore-config.  It works exactly like the older one did and in
ImageMagick 6 returns exactly the same values for all requested flags.
Magick 7 deleted the old script.
We now first look for MagickCore-config and
set MAGIC_BIN to that path if we find it.  If we don't find it, we
look for Magick-config and set MAGIC_BIN to that path if we find it.
This commit closes #147.
It does not in fact allow Magick 7 to work with Xastir, but that's
another …
> Use MagickCore-config if available

- acinclude.m4
- src/main.c
- src/map_OSM.c
- src/map_WMS.c
- src/map_geo.c
- src/maps.c
Even after the fixes of #23 and #40, we missed some ImageMagick deprecation warnings in main.c and map_geo.c.
This PR fixes those so that Xastir builds cleanly with ImageMagick 6.
I was unable to get ImageMagick 7 to build with these changes, and so put code into acinclude.m4 to reject versions of Magick with MagickLibVersion greater than 0x0700.  This may have been overly conservative, because the errors I saw when trying to build Xastir with my system's ImageMagick 7 might have been due entirely to the default package being built with HDRI support.
Anyone willing to start looking into bug #148 would be well-advised to make sure to start from a version if IM7 that has HDRI support disabled.
We should also probably put a test into configure that checks how IM was built and rejects it if …
> Remove ImageMagick version 6 deprecation warnings

- .travis.yml
- configure.ac
- src/dbfawk.c
- src/map_shp.c
- src/maps.c
- src/testdbfawk.c
This PR closes bug #128 
We now require PCRE if shapelib support is needed, and always enable dbfawk.
Configure now no longer allows the user to specifically request "--without-dbfawk" or "--without-pcre".  One can still request "--without-shapelib".
If shapelib support is requested and shapelib found at configure time, we look for pcre.  If pcre is found, all is good.  If pcre is NOT found, we error out and tell the user either to disable shapelib support OR install pcre.
I have also removed from the Travis-CI config all tests that try to use "--without-dbfawk" or "--without-pcre".  Only the one with "--without-shapelib" remains.
> Make dbfawk the only way to render shapefiles

- scripts/Makefile.am
As of 93950da37ad18f2f50426b8008522e8b8115b75b, there is no longer a .py script to chmod.  (This prevents `make install-data-hook` from puking.)
> No longer attempt to chmod *.py in scripts/Makefile

- scripts/get-gnis.in
Zip files can now be downloaded without a date stamp,
but the unzipped file still has a date stamp in the filename.
Determine the unzipped filename on the fly so the date stamp
does not need to be hard coded.
Closes #162
> Update get-gnis to not use date stamps for zip files

- scripts/get-NWSdata.in
Fixes an issue where the dbfawk test fails on non /usr/local prefix paths by making the usage at the test step consistent with the download step based on the defined prefix path.
> Use prefix path consistently for dbfawk test as well as download

- src/db.c
This code can cause a buffer overflow of small_string, which will
result in a core dump when Xastir is compiled with -fstack-protector.
https://github.com/Xastir/Xastir/issues/174
> Remove buggy, unused diagnostic code.

- acinclude.m4
Today, I was submitting a patch to the FreeBSD ports system to update
the port from 2.1.6 to 2.1.8, and found that it was easy to do so, but
that the port failed to detect "gv" even though it was installed.  This has 
apparently always been the case, and the port maintainer never bothered
us about it --- a version of Xastir built from the port system would simply
never use gv, and so a user couldn't print maps.  I guess nobody bothered
about it.  But seeing this problem made me want to fix it, and I have.
The reason for this is that Xastir's configure actually runs "\`gv
--version 2>&1\`" to get the gv version, and this is strictly Bourne
shell syntax.  The default shell for the root user on FreeBSD is csh,
not bash, and therefor the "2>&1" syntax is actually an error and
causing the …
> Remove bashism from acinclude.m4

- Davis/README
- Davis/src/db2APRS.c
- LaCrosse/README
- LaCrosse/src/open2300db2APRS.c
- src/dlm.c
- src/main.c
Found using codespell:
codespell --skip *.dat,LICENSE,./src/snprintf.c,./scripts/langOldeEnglish.pl,./scripts/langPirateEnglish.pl --ignore-words-list 3st,bu,cancl,clen,herat,ists,lond,ro,templat,writen
> Fix typing errors

- configure.ac
- src/awk.c
- src/awk.h
- src/dbfawk.c
- src/map_shp.c
- src/testdbfawk.c
This pull request adds PCRE2 support to Xastir, while maintaining support for legacy PCRE.
If PCRE2 is found (first by finding "pcre2.h" and then by finding "libpcre2-8"), we use it.  Only if it is NOT found (or doesn't work because of pathing or other issues) then we probe for legacy PCRE as we always have.  If neither works, we puke saying we can't support shapelib without a version of PCRE and tell the user to install it or disable shapefile support.
I have tested this primarily by using the "testdbfawk" program over a handful of complex shapefiles I have.  I have confirmed that testdbfawk produces identical parsing and handling of shapefiles with either version of PCRE, and have tested the fallback mechanism multiple times --- Xastir compiles and links with either version of PCRE and …
> Issue 203 -- Add support for PCRE2

- src/map_shp.c
In issue #156 it was reported that Xastir's defaults make it so that a shapefile that has no associated dbfawk file does not correctly get displayed at all zoom levels.  There are two reasons for this.
One, the default_dbfawk_rules defines a display level of 65536 which is very small compared to the possible world-level zoom.  This rule is used when no dbfawk file is found.
The second problem is that elsewhere in the code we set display_level to 8192.  This much, much older value used to be the same in default_dbfawk_rules, but the default rules were updated in commit 56b7e30 to the higher value.  This value is only used when there *is* an associated dbfawk file, but that file fails to initialize display_level in the BEGIN record.
This commit makes the default in default_dbfawk_rules to …
> Issue 156 -- Fix default display_level to be consistent and huge

- src/main.c
- src/map_OSM.c
- src/map_WMS.c
- src/map_geo.c
In olden times, the ImageMagick API was quite unstable and kept changing out from underneath us.  Because it had not yet made it into package management systems, most users of Xastir that needed ImageMagick at the time *also* needed to compile it themselves from source.  As a result, many of them would not want to recompile the very latest version of ImageMagick every time an API got broken, but neither would new users want to have to stick to an old version. Xastir code was therefore peppered with all manner of ifdefs to handle every old version of ImageMagick one might have installed.
The first of these ifdefs was already present in 2002 when Xastir was first imported into CVS.  New ifdefs were added in 2002, 2003, and a final set in 2018.  There have been no more new versions of …
> Remove workarounds for ancient versions of ImageMagick

- src/list_gui.c
The setup of the callback when an icon is clicked in the station list dialogs uses the callsign from the station name column to locate the desired station. The name was updated after the callback was set, so in a changing environment the callback would display the location of the station that previously occupied that row in the list.
Move the updating of the name to be before setting up the icon.
> Issue 199 -- Move code to fix locate callback

- .github/workflows/linux-build.yml
- .github/workflows/test-build.yml
Use GitHub actions to do a test build on ubuntu (both a smaller scale and full-featured version, minus kernel AX25) and on macOS.
> Add GitHub Actions to test build for linux MacOS
