scripts/get-gnis

New URL (301 redirect from http) and new suffix.

Updated file name and URL (https)

---

src/dlm.c

While DLM_queue_state is not at risk of getting corrupted by
multiple threads writing to it, we still should protect it with
a mutex to ensure a consistent view of memory between threads.
I also moved the DLM thread start/stop prints to be under debug
level 1.

Add mutex protection to DLM_queue_state

---

.travis.yml
src/messages_gui.c
src/objects.c
src/rac_data.c
src/sound.c
src/tile_mgmnt.c
src/track_gui.c
src/util.c
src/wx.c
src/wx_gui.c
src/xa_config.c

Looks like I fixed compiler warnings for the three Linux Travis-CI builds but not the OSX build. It's a start!

Fixing compiler warnings

---

src/messages.c

Fixes messages.c warning. Continuing my march Northward as Tom continues South. This will test my pushed branch / merging with the main project / deleting my branch from Github & locally / starting development over with the next feature branch.

Get rid of compiler warning

---

src/map_WMS.c
src/map_geo.c
src/map_pdb.c
src/map_shp.c
src/map_tif.c
src/objects.c
src/rotated.c
src/wx_gui.c
src/x_spider.c
src/x_spider.h

Partial fix for bug #24. Fix compiler warnings plus get rid of "register" keyword where used.

Warning fixes 2

---

src/map_dos.c
src/maps.c

Fix more unused variables. Solves a portion of bug #24.

Warning fixes 3

---

src/interface_gui.c

Commented out variable names, removed variable assignments from
GUI elements whose variable didn't get used. Partial fix to bug #24.

Fix compiler warnings

---

src/forked_getaddrinfo.c

Part of bug #24. Checking return status of read/write calls. I don't do anything in the error handler in order to mimic the behavior before when we didn't check return status at all.

Check return value for read/write functions

---

.travis.yml

Simple change: Moving CFLAGS to env: section of Travis-CI config.

Move CFLAGS to env: section

---

configure.ac

Rename "Disable Map Caching" to "Disable Berkely DB Map Caching"
in the configure tests, change name in summary list similarly.
Extend other lines in summary so they line up nicely.

Minor renaming of config option

---

src/map_OSM.c
src/map_geo.c
src/map_tif.c
src/messages.c
src/objects.c
src/testdbfawk.c

Implemented a bunch of fixes for compiler warnings that were showing up in the OSX build. This is part of the fix for bug #24.

Osx warnings

---

src/map_geo.c
src/map_tif.c
src/track_gui.c

A fix for issue #72 and partial fix for issue #24. This changes some of the fixes that were done in pull request #104. It fixes some of the casting to other data types that were incorrect or poorly done in PR #104.

Osx warnings2

---

.travis.yml

Adding libxpm-dev package to Ubuntu builds.

Adding libXpm-dev package

---

.vimrc
Davis/.vimrc
LaCrosse/.vimrc
callpass/.vimrc
config/.vimrc
help/.vimrc
intl/.vimrc
po/.vimrc
scripts/.vimrc
src/.vimrc
src/rtree/.vimrc
symbols/.vimrc

Add .vimrc per directory which specifies  Xastir source-code settings
for the Vim editor.

Add per-directory Vim project-specific settings

---

.travis.yml

Enable Davis builds in travis for Mac

---

src/objects.h
src/x_spider.c
src/x_spider.h
src/xa_config.c
src/xa_config.h

Fixes build error when compiled with -fno-common or GCC-10

---

src/db.c
src/draw_symbols.c
src/geocoder_gui.c
src/interface_gui.c
src/locate_gui.c
src/location_gui.c
src/main.c
src/maps.c
src/messages_gui.c
src/objects.c
src/popup_gui.c
src/track_gui.c
src/view_message_gui.c
src/wx_gui.c
src/xastir.h

More fixes for dialogs w/scrollbars. This resizes properly on my system for small screens and large. Results may vary based on window manager selection/settings and font selection. More to do yet as not all dialogs have the new code added.

Further rework dialogs to support small screens

---

src/x_spider.c

If xastir crashed it would leave child processes for the UDP server
still running. Switch the poll() to timeout after 5 seconds and then
use kill() to see if the parent is still alive.
Fixes #130.

Have UDP server check that parent is still alive.

---

src/interface.c

Initialize addrinfo structure to 0.

---

src/interface.c

Xastir was improperly putting "A=xxxxxx/" into the comment field of position reports with PHG.  This is only done for fixed stations with GPS attached (the only ones that have altitude to report).  The reason it doesn't get done correctly is that there was a logic error in the code that was intended to insert a slash before the altitude in just the fixed-station+PHG cases.
It has been wrong since at least 2002.
The problem is that the spec requires "/A=xxxxxx" for the altitude to be recognized.
In other parts of the code, where we're adding altitude to course and speed, we were unnecessarily putting a "/" at the end of course and speed, then conditionally adding "/" in between that and the altitude string depending on whether it had already been added or not.  This is unnecessarily …

Fix altitude-in-comment with PHG

---

scripts/get-NWSdata.in

Updates the get-NWSdata script to the current versions of the shapefiles

Update to latest version of the NWS shapefiles

---

acinclude.m4

Way back in 2004 when map caching was added to Xastir, a set of autoconf macros was copied from another project to detect which Berkeley DB libraries to use.  This set of macros was kept for the last 20 years, with only minor tweaks.
However, the thing it did was very much similar to the standard "AC_SEARCH_LIBS" autoconf macro, but clumsier.
It was incorrectly assumed that one must include "db.h" in the test program for db_create, which means one must also provide a test program that uses db_create with all its required arguments --- something AC_SEARCH_LIBS cannot do.
This commit vastly simplifies the XASTIR_BERKELEY_DB_CHK_LIB macro to rip out all the convoluted looping and conditionals, and replace it all with a call to AC_SEARCH_LIBS with a big list of possible libraries. …

Greatly simplify Berkeley DB library search

---

symbols/Makefile.am
symbols/icon.svg

Add a SVG icon for Xastir
